export interface Project {
  slug: string
  name: string
  tagline: string
  description: string
  longDescription: string
  type: string
  bedrooms: string
  bathrooms: string
  priceFrom: string
  units: number
  area: string
  landArea: string
  poolSize: string
  status: 'Selling' | 'Coming Soon' | 'Under Construction' | 'Sold Out'
  location: string
  features: string[]
  accentColor: string
  gradientFrom: string
  gradientTo: string
  images: string[]
  thumbnail: string
  mapEmbed?: string
  mapLink?: string
  floorPlans?: string[] // floor-plan cards (replaces the generic floor-plan placeholder)
  youtubeId?: string // YouTube video (replaces the 3D visualisation placeholder)
  offer?: string // "OFFER" button link (e.g. Canva presentation)
  realImages?: string[] // completed-development photos → "render vs reality" proof
  construction?: string[] // construction-progress gallery
  locationImage?: string // illustrated location map with key points
  inquiryOnly?: boolean // not a standard investment unit (hides payment schedule)
  bookingUrl?: string // delivered/rentable project — show a "book your stay" CTA instead of payment schedule
}

export const projects: Project[] = [
  {
    slug: 'harmony-life-one',
    name: 'Harmony Life One',
    tagline: '10 Boho Villas — Fully Sold Out',
    description: 'Our debut project — 10 boho-style villas sold out on launch. The vision that started it all.',
    longDescription: 'Harmony Life One was our first project and a resounding success — all 10 villas were sold before completion. Each villa was carefully designed with a boho aesthetic and European construction standards, offering 2–3 bedrooms and 136–197 m² of living space on Koh Samui. The project proved that international buyers were ready for European-quality builds on the island.',
    type: 'Villas',
    bedrooms: '2–3',
    bathrooms: '3',
    priceFrom: 'Sold Out',
    units: 10,
    area: '136–197 m²',
    landArea: 'N/A',
    poolSize: 'Private pool',
    status: 'Sold Out',
    location: 'Koh Samui',
    features: [
      'Boho-style architecture',
      'Private pool per villa',
      'European construction standards',
      '2–3 bedrooms',
      '3 bathrooms',
      'Tropical garden',
      'Smart home system',
      'Full management available',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#2D4A3E',
    gradientTo: '#1a2e24',
    thumbnail: '/images/projects/harmony-life-one/08.webp',
    images: [
      '/images/projects/harmony-life-one/01.webp',
      '/images/projects/harmony-life-one/02.webp',
      '/images/projects/harmony-life-one/03.webp',
      '/images/projects/harmony-life-one/04.webp',
      '/images/projects/harmony-life-one/05.webp',
      '/images/projects/harmony-life-one/06.webp',
      '/images/projects/harmony-life-one/07.webp',
      '/images/projects/harmony-life-one/08.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.5483084,100.0526437&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/JUGLbQrzHQAQDXbu7',
    realImages: Array.from({ length: 26 }, (_, i) => `/images/projects/harmony-life-one/real/${String(i + 1).padStart(2, '0')}.webp`),
    bookingUrl: 'https://www.harmonylife.asia',
  },
  {
    slug: 'harmony-life-hill',
    name: 'Harmony Life Hill',
    tagline: 'Hillside Pool Villas — Fully Sold Out',
    description: '6 exclusive hillside villas with panoramic ocean views — sold out. Perched above the island with breath-taking views.',
    longDescription: 'Harmony Life Hill is a complex of exclusive villas set on the hills of Koh Samui, each with panoramic views of the ocean and tropical landscape. Every villa features 3 bedrooms, 3 bathrooms, 240 m² of living space, a private pool, and terraces with spectacular views. The project is fully sold out — a testament to the enduring demand for quality on Koh Samui.',
    type: 'Pool Villas',
    bedrooms: '3',
    bathrooms: '3',
    priceFrom: 'Sold Out',
    units: 6,
    area: '240 m²',
    landArea: 'Hillside plot',
    poolSize: 'Private infinity pool',
    status: 'Sold Out',
    location: 'Hillside, Koh Samui',
    features: [
      'Panoramic ocean views',
      'Private infinity pool',
      '3 bedrooms + 3 bathrooms',
      '240 m² living space',
      'Private terraces',
      'European construction',
      'Modern architecture',
      'Privacy & exclusivity',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#1a2e3e',
    gradientTo: '#0d1a2e',
    thumbnail: '/images/projects/harmony-life-hill/01.webp',
    images: [
      '/images/projects/harmony-life-hill/01.webp',
      '/images/projects/harmony-life-hill/02.webp',
      '/images/projects/harmony-life-hill/03.webp',
      '/images/projects/harmony-life-hill/04.webp',
      '/images/projects/harmony-life-hill/05.webp',
      '/images/projects/harmony-life-hill/06.webp',
      '/images/projects/harmony-life-hill/07.webp',
      '/images/projects/harmony-life-hill/08.webp',
      '/images/projects/harmony-life-hill/09.webp',
      '/images/projects/harmony-life-hill/10.webp',
      '/images/projects/harmony-life-hill/11.webp',
      '/images/projects/harmony-life-hill/12.webp',
      '/images/projects/harmony-life-hill/13.webp',
      '/images/projects/harmony-life-hill/14.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.547741,100.049985&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/8sUwh8V3YPaLmvoPA',
    floorPlans: [
      '/images/projects/harmony-life-hill/plan-01.webp',
      '/images/projects/harmony-life-hill/plan-02.webp',
    ],
    construction: [
      '/images/projects/harmony-life-hill/construction/01.webp',
      '/images/projects/harmony-life-hill/construction/02.webp',
      '/images/projects/harmony-life-hill/construction/03.webp',
      '/images/projects/harmony-life-hill/construction/04.webp',
      '/images/projects/harmony-life-hill/construction/05.webp',
      '/images/projects/harmony-life-hill/construction/06.webp',
      '/images/projects/harmony-life-hill/construction/07.webp',
      '/images/projects/harmony-life-hill/construction/08.webp',
      '/images/projects/harmony-life-hill/construction/09.webp',
    ],
    youtubeId: 'oSSdVyCl41Q',
  },
  {
    slug: 'harmony-life-hill-2',
    name: 'Harmony Life Hill 2',
    tagline: '5 Premium Hillside Villas — Phase Two',
    description: 'The second phase of our award-winning Hill project. 5 even more spacious premium villas with infinity pools and panoramic ocean terraces.',
    longDescription: 'Harmony Life Hill 2 builds on the success of the first phase, offering 5 even more spacious and luxurious villas. Each property features 3 bedrooms, 3 bathrooms, 200 m² of living space, a private infinity pool, and expansive terraces with panoramic views of the ocean and tropical landscape. The project combines modern design with tropical elements and the finest finishing materials.',
    type: 'Premium Villas',
    bedrooms: '3',
    bathrooms: '3',
    priceFrom: 'Contact for pricing',
    units: 5,
    area: '200 m²',
    landArea: 'Hillside plot',
    poolSize: 'Private infinity pool',
    status: 'Selling',
    location: 'Hillside, Koh Samui',
    features: [
      'Panoramic ocean & jungle views',
      'Private infinity pool',
      '3 bedrooms + 3 bathrooms',
      '200 m² living space',
      'Expansive ocean-view terraces',
      'Top-grade finishing materials',
      'Modern tropical architecture',
      'European construction standards',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#1a2e3a',
    gradientTo: '#0d1e2e',
    thumbnail: '/images/projects/harmony-life-hill-2/01.webp',
    images: [
      '/images/projects/harmony-life-hill-2/01.webp',
      '/images/projects/harmony-life-hill-2/02.webp',
      '/images/projects/harmony-life-hill-2/03.webp',
      '/images/projects/harmony-life-hill-2/04.webp',
      '/images/projects/harmony-life-hill-2/05.webp',
      '/images/projects/harmony-life-hill-2/06.webp',
      '/images/projects/harmony-life-hill-2/07.webp',
      '/images/projects/harmony-life-hill-2/08.webp',
      '/images/projects/harmony-life-hill-2/09.webp',
      '/images/projects/harmony-life-hill-2/10.webp',
      '/images/projects/harmony-life-hill-2/11.webp',
      '/images/projects/harmony-life-hill-2/12.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.547485,100.049810&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/uxhTfe3ri1rPHRKe9',
    floorPlans: [
      '/images/projects/harmony-life-hill/plan-01.webp',
      '/images/projects/harmony-life-hill/plan-02.webp',
    ],
    construction: [
      '/images/projects/harmony-life-hill-2/construction/01.webp',
    ],
  },
  {
    slug: 'harmony-life-oasis',
    name: 'Harmony Life Oasis',
    tagline: '53 Sea-View Villas — Tropical Oasis',
    description: 'A tropical oasis of 53 exclusive sea-view villas in diverse layouts from 1 to 4 bedrooms — for every investor and lifestyle buyer.',
    longDescription: 'Harmony Life Oasis is an extraordinary project offering 53 luxury villas designed as a true tropical oasis. The development provides a wide range of layouts — from 1 to 4 bedrooms, with areas from 90 to 345 m² — each with breath-taking sea views. Onsite amenities include an exclusive café and a professional kids club, making this project ideal for both investors seeking rental yields and families planning to live on Koh Samui permanently.',
    type: 'Villas',
    bedrooms: '1–4',
    bathrooms: '1–4',
    priceFrom: '฿6.2M · $190,000',
    units: 53,
    area: '90–345 m²',
    landArea: 'Various',
    poolSize: 'Private pool',
    status: 'Selling',
    location: 'Koh Samui',
    features: [
      'Sea views from all units',
      '1–4 bedroom layouts',
      '90–345 m² living areas',
      'On-site café',
      'Professional kids club',
      'Private pool per villa',
      'European quality construction',
      'Rental management available',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#2a3a2a',
    gradientTo: '#1a2e1a',
    thumbnail: '/images/projects/harmony-life-oasis/gallery/01.webp',
    images: [
      '/images/projects/harmony-life-oasis/gallery/01.webp',
      '/images/projects/harmony-life-oasis/gallery/02.webp',
      '/images/projects/harmony-life-oasis/gallery/03.webp',
      '/images/projects/harmony-life-oasis/gallery/04.webp',
      '/images/projects/harmony-life-oasis/gallery/05.webp',
      '/images/projects/harmony-life-oasis/gallery/06.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.565041,100.070399&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/czYyjxXiJLCNtgww9',
    offer: 'https://canva.link/1fsfd05xf53qpy5',
  },
  {
    slug: 'solaya-residence',
    name: 'SOLAYA Residence',
    tagline: 'Sea-view villas · Plai Laem',
    description: 'Modern 2–3 bedroom sea-view villas in Plai Laem — European build quality, fully managed by Harmony Life.',
    longDescription: 'SOLAYA Residence is a new Harmony Life villa project in the prestigious Plai Laem district of Koh Samui: 2–3 bedroom villas, including a flagship type with a private rooftop terrace. Every villa has a sea or panoramic view, a private pool and tropical garden. European build quality, a leasehold structure registered with the Land Department, and full rental management by one team — from construction to quarterly settlements.',
    type: 'Premium Villas',
    bedrooms: '2–3 BR',
    bathrooms: '2–3',
    priceFrom: 'On request',
    units: 0,
    area: '—',
    landArea: '—',
    poolSize: 'Private pool',
    status: 'Selling',
    location: 'Plai Laem, Koh Samui',
    features: [
      'Sea or panoramic views',
      '2–3 bedroom villas',
      'Private pool & tropical garden',
      'Flagship rooftop-terrace type',
      'European build quality',
      'Full rental management',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#1e2e2a',
    gradientTo: '#1a1a2e',
    thumbnail: '/images/projects/solaya/aerial/04.webp',
    images: [
      '/images/projects/solaya/aerial/04.webp',
      '/images/projects/solaya/aerial/04.webp',
      '/images/projects/solaya/aerial/04.webp',
      '/images/projects/solaya/aerial/04.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.566021,100.068411&z=15&output=embed',
    mapLink: 'https://maps.app.goo.gl/WUvviriZTrdL1kSb7',
    offer: 'https://panel.harmonylife.asia/p/SOLV/units',
  },
  {
    slug: 'harmony-life-wellness',
    name: 'Harmony Life Wellness & Caffe',
    tagline: 'Wellness, Spa & Café — by individual arrangement',
    description: 'A wellness sanctuary with spa, massage and an artisan café — for the residents and guests of Harmony Life. Available by individual arrangement, not a standard investment unit.',
    longDescription: 'Harmony Life Wellness & Caffe is the calm, social heart of the Harmony Life world — a dedicated space for spa rituals, massage and body treatments, sauna and ice-bath recovery, and an artisan café to slow down in. It is designed for our owners and their guests, wellness travellers, and anyone on Koh Samui looking for genuine balance and rest. This is not a standard investment unit — any involvement is arranged individually, case by case. Reach out and we will walk you through the options.',
    type: 'Wellness & Café',
    bedrooms: '—',
    bathrooms: '—',
    priceFrom: 'On request',
    units: 0,
    area: '—',
    landArea: '—',
    poolSize: 'Spa & pool',
    status: 'Under Construction',
    location: 'Koh Samui',
    features: [
      'Spa & treatment rooms',
      'Massage & body therapies',
      'Sauna & ice-bath recovery',
      'Artisan café',
      'For residents, guests & wellness travellers',
      'By individual arrangement',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#2e2a1a',
    gradientTo: '#1a160d',
    thumbnail: '/images/projects/harmony-life-wellness/01.webp',
    images: [
      '/images/projects/harmony-life-wellness/01.webp',
      '/images/projects/harmony-life-wellness/02.webp',
      '/images/projects/harmony-life-wellness/03.webp',
      '/images/projects/harmony-life-wellness/04.webp',
      '/images/projects/harmony-life-wellness/05.webp',
      '/images/projects/harmony-life-wellness/06.webp',
      '/images/projects/harmony-life-wellness/07.webp',
      '/images/projects/harmony-life-wellness/08.webp',
      '/images/projects/harmony-life-wellness/09.webp',
      '/images/projects/harmony-life-wellness/10.webp',
      '/images/projects/harmony-life-wellness/11.webp',
      '/images/projects/harmony-life-wellness/12.webp',
    ],
    youtubeId: '9tuCrJfeEzk',
    mapEmbed: 'https://www.google.com/maps?q=9.5688738,100.0618841&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/Kbf7tp4tnsQGu9558',
    inquiryOnly: true,
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}
