export interface Project {
  slug: string
  name: string
  tagline: string
  description: string
  longDescription: string
  type: string
  bedrooms: string
  bathrooms: string
  priceFrom: string
  units: number
  area: string
  landArea: string
  poolSize: string
  status: 'Selling' | 'Coming Soon' | 'Under Construction' | 'Sold Out'
  location: string
  features: string[]
  accentColor: string
  gradientFrom: string
  gradientTo: string
  images: string[]
  thumbnail: string
  mapEmbed?: string
  mapLink?: string
  floorPlans?: string[] // floor-plan cards (replaces the generic floor-plan placeholder)
  youtubeId?: string // YouTube video (replaces the 3D visualisation placeholder)
  offer?: string // "OFFER" button link (e.g. Canva presentation)
  realImages?: string[] // completed-development photos → "render vs reality" proof
}

export const projects: Project[] = [
  {
    slug: 'harmony-life-one',
    name: 'Harmony Life One',
    tagline: '10 Boho Villas — Fully Sold Out',
    description: 'Our debut project — 10 boho-style villas sold out on launch. The vision that started it all.',
    longDescription: 'Harmony Life One was our first project and a resounding success — all 10 villas were sold before completion. Each villa was carefully designed with a boho aesthetic and European construction standards, offering 2–3 bedrooms and 136–197 m² of living space on Koh Samui. The project proved that international buyers were ready for European-quality builds on the island.',
    type: 'Villas',
    bedrooms: '2–3',
    bathrooms: '3',
    priceFrom: 'Sold Out',
    units: 10,
    area: '136–197 m²',
    landArea: 'N/A',
    poolSize: 'Private pool',
    status: 'Sold Out',
    location: 'Koh Samui',
    features: [
      'Boho-style architecture',
      'Private pool per villa',
      'European construction standards',
      '2–3 bedrooms',
      '3 bathrooms',
      'Tropical garden',
      'Smart home system',
      'Full management available',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#2D4A3E',
    gradientTo: '#1a2e24',
    thumbnail: '/images/projects/harmony-life-one/08.webp',
    images: [
      '/images/projects/harmony-life-one/01.webp',
      '/images/projects/harmony-life-one/02.webp',
      '/images/projects/harmony-life-one/03.webp',
      '/images/projects/harmony-life-one/04.webp',
      '/images/projects/harmony-life-one/05.webp',
      '/images/projects/harmony-life-one/06.webp',
      '/images/projects/harmony-life-one/07.webp',
      '/images/projects/harmony-life-one/08.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.5483084,100.0526437&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/JUGLbQrzHQAQDXbu7',
    realImages: Array.from({ length: 26 }, (_, i) => `/images/projects/harmony-life-one/real/${String(i + 1).padStart(2, '0')}.webp`),
  },
  {
    slug: 'harmony-life-hill',
    name: 'Harmony Life Hill',
    tagline: 'Hillside Pool Villas — Fully Sold Out',
    description: '6 exclusive hillside villas with panoramic ocean views — sold out. Perched above the island with breath-taking views.',
    longDescription: 'Harmony Life Hill is a complex of exclusive villas set on the hills of Koh Samui, each with panoramic views of the ocean and tropical landscape. Every villa features 3 bedrooms, 3 bathrooms, 240 m² of living space, a private pool, and terraces with spectacular views. The project is fully sold out — a testament to the enduring demand for quality on Koh Samui.',
    type: 'Pool Villas',
    bedrooms: '3',
    bathrooms: '3',
    priceFrom: 'Sold Out',
    units: 6,
    area: '240 m²',
    landArea: 'Hillside plot',
    poolSize: 'Private infinity pool',
    status: 'Sold Out',
    location: 'Hillside, Koh Samui',
    features: [
      'Panoramic ocean views',
      'Private infinity pool',
      '3 bedrooms + 3 bathrooms',
      '240 m² living space',
      'Private terraces',
      'European construction',
      'Modern architecture',
      'Privacy & exclusivity',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#1a2e3e',
    gradientTo: '#0d1a2e',
    thumbnail: '/images/projects/harmony-life-hill/01.webp',
    images: [
      '/images/projects/harmony-life-hill/01.webp',
      '/images/projects/harmony-life-hill/02.webp',
      '/images/projects/harmony-life-hill/03.webp',
      '/images/projects/harmony-life-hill/04.webp',
      '/images/projects/harmony-life-hill/05.webp',
      '/images/projects/harmony-life-hill/06.webp',
      '/images/projects/harmony-life-hill/07.webp',
      '/images/projects/harmony-life-hill/08.webp',
      '/images/projects/harmony-life-hill/09.webp',
      '/images/projects/harmony-life-hill/10.webp',
      '/images/projects/harmony-life-hill/11.webp',
      '/images/projects/harmony-life-hill/12.webp',
      '/images/projects/harmony-life-hill/13.webp',
      '/images/projects/harmony-life-hill/14.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.547741,100.049985&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/8sUwh8V3YPaLmvoPA',
    floorPlans: [
      '/images/projects/harmony-life-hill/plan-01.webp',
      '/images/projects/harmony-life-hill/plan-02.webp',
    ],
    youtubeId: 'oSSdVyCl41Q',
  },
  {
    slug: 'harmony-life-hill-2',
    name: 'Harmony Life Hill 2',
    tagline: '5 Premium Hillside Villas — Phase Two',
    description: 'The second phase of our award-winning Hill project. 5 even more spacious premium villas with infinity pools and panoramic ocean terraces.',
    longDescription: 'Harmony Life Hill 2 builds on the success of the first phase, offering 5 even more spacious and luxurious villas. Each property features 3 bedrooms, 3 bathrooms, 200 m² of living space, a private infinity pool, and expansive terraces with panoramic views of the ocean and tropical landscape. The project combines modern design with tropical elements and the finest finishing materials.',
    type: 'Premium Villas',
    bedrooms: '3',
    bathrooms: '3',
    priceFrom: 'Contact for pricing',
    units: 5,
    area: '200 m²',
    landArea: 'Hillside plot',
    poolSize: 'Private infinity pool',
    status: 'Selling',
    location: 'Hillside, Koh Samui',
    features: [
      'Panoramic ocean & jungle views',
      'Private infinity pool',
      '3 bedrooms + 3 bathrooms',
      '200 m² living space',
      'Expansive ocean-view terraces',
      'Top-grade finishing materials',
      'Modern tropical architecture',
      'European construction standards',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#1a2e3a',
    gradientTo: '#0d1e2e',
    thumbnail: '/images/projects/harmony-life-hill-2/01.webp',
    images: [
      '/images/projects/harmony-life-hill-2/01.webp',
      '/images/projects/harmony-life-hill-2/02.webp',
      '/images/projects/harmony-life-hill-2/03.webp',
      '/images/projects/harmony-life-hill-2/04.webp',
      '/images/projects/harmony-life-hill-2/05.webp',
      '/images/projects/harmony-life-hill-2/06.webp',
      '/images/projects/harmony-life-hill-2/07.webp',
      '/images/projects/harmony-life-hill-2/08.webp',
      '/images/projects/harmony-life-hill-2/09.webp',
      '/images/projects/harmony-life-hill-2/10.webp',
      '/images/projects/harmony-life-hill-2/11.webp',
      '/images/projects/harmony-life-hill-2/12.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.547485,100.049810&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/uxhTfe3ri1rPHRKe9',
    floorPlans: [
      '/images/projects/harmony-life-hill/plan-01.webp',
      '/images/projects/harmony-life-hill/plan-02.webp',
    ],
  },
  {
    slug: 'harmony-life-oasis',
    name: 'Harmony Life Oasis',
    tagline: '53 Sea-View Villas — Tropical Oasis',
    description: 'A tropical oasis of 53 exclusive sea-view villas in diverse layouts from 1 to 4 bedrooms — for every investor and lifestyle buyer.',
    longDescription: 'Harmony Life Oasis is an extraordinary project offering 53 luxury villas designed as a true tropical oasis. The development provides a wide range of layouts — from 1 to 4 bedrooms, with areas from 97 to 358 m² — each with breath-taking sea views. Onsite amenities include an exclusive café and a professional kids club, making this project ideal for both investors seeking rental yields and families planning to live on Koh Samui permanently.',
    type: 'Premium Villas',
    bedrooms: '1–4',
    bathrooms: '1–4',
    priceFrom: '฿6.2M · $190,000',
    units: 53,
    area: '97–358 m²',
    landArea: 'Various',
    poolSize: 'Private pool',
    status: 'Selling',
    location: 'Koh Samui',
    features: [
      'Sea views from all units',
      '1–4 bedroom layouts',
      '97–358 m² living areas',
      'On-site café',
      'Professional kids club',
      'Private pool per villa',
      'European quality construction',
      'Rental management available',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#2a3a2a',
    gradientTo: '#1a2e1a',
    thumbnail: '/images/projects/harmony-life-oasis/gallery/01.webp',
    images: [
      '/images/projects/harmony-life-oasis/gallery/01.webp',
      '/images/projects/harmony-life-oasis/gallery/02.webp',
      '/images/projects/harmony-life-oasis/gallery/03.webp',
      '/images/projects/harmony-life-oasis/gallery/04.webp',
      '/images/projects/harmony-life-oasis/gallery/05.webp',
      '/images/projects/harmony-life-oasis/gallery/06.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.565041,100.070399&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/czYyjxXiJLCNtgww9',
    offer: 'https://canva.link/1fsfd05xf53qpy5',
  },
  {
    slug: 'solaya-residence',
    name: 'Solaya Residence',
    tagline: '71 Sea-View Apartments in Plai Leam',
    description: 'A modern complex of 71 premium apartments with sea views in Plai Leam — from intimate studios to spacious 2-bedroom apartments.',
    longDescription: "Solaya Residence is a modern complex of 71 premium apartments with stunning sea views in the sought-after Plai Leam district of Koh Samui. The project combines elegant design with functionality and the highest comfort standards. Layouts range from intimate studios to spacious 2-bedroom apartments, 39–92 m². The development stands out for its exceptional amenity infrastructure: a lagoon pool, fully equipped gym, saunas, luxury spa, and fine dining restaurant. The complex is also designed for professional retreats, making it an exceptional place on Koh Samui's map — perfect for living and as a high-yield investment.",
    type: 'Premium Apartments',
    bedrooms: 'Studio–2BR',
    bathrooms: '1–2',
    priceFrom: 'Contact for pricing',
    units: 71,
    area: '39–92 m²',
    landArea: 'N/A',
    poolSize: 'Lagoon pool (shared)',
    status: 'Selling',
    location: 'Plai Leam, Koh Samui',
    features: [
      'Sea views from all units',
      'Studio, 1BR & 2BR layouts',
      '39–92 m² living areas',
      'Lagoon pool',
      'Luxury spa',
      'Fully equipped gym & saunas',
      'Fine dining restaurant',
      'Retreat-ready facilities',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#2e1a2e',
    gradientTo: '#1a0d2e',
    thumbnail: '/images/projects/solaya-residence/exterior/01.webp',
    images: [
      '/images/projects/solaya-residence/exterior/01.webp',
      '/images/projects/solaya-residence/exterior/02.webp',
      '/images/projects/solaya-residence/exterior/03.webp',
      '/images/projects/solaya-residence/exterior/04.webp',
      '/images/projects/solaya-residence/exterior/05.webp',
      '/images/projects/solaya-residence/exterior/06.webp',
    ],
    mapEmbed: 'https://www.google.com/maps?q=9.565746,100.068217&z=16&output=embed',
    mapLink: 'https://maps.app.goo.gl/gqBbTv8hdYpRrMdNA',
    offer: 'https://canva.link/98qt55epbh7v4pw',
  },
  {
    slug: 'harmony-life-wellness',
    name: 'Harmony Life Wellness & Caffe',
    tagline: 'Wellness Sanctuary — Coming Soon',
    description: 'A wellness sanctuary and artisan café experience — the next chapter in the Harmony Life story. Register your interest for priority updates.',
    longDescription: 'Harmony Life Wellness & Caffe represents a new dimension of the Harmony Life vision — a dedicated wellness sanctuary and café experience. Full details will be revealed soon. Register your interest today to receive priority access to floor plans, pricing, and launch information.',
    type: 'Wellness & Caffe',
    bedrooms: 'TBA',
    bathrooms: 'TBA',
    priceFrom: 'TBA',
    units: 0,
    area: 'TBA',
    landArea: 'TBA',
    poolSize: 'TBA',
    status: 'Under Construction',
    location: 'Koh Samui',
    features: [
      'Wellness sanctuary',
      'Artisan café',
      'Details coming soon',
      'Register interest for priority access',
    ],
    accentColor: '#C9A876',
    gradientFrom: '#2e2a1a',
    gradientTo: '#1a160d',
    thumbnail: '/images/about.webp',
    images: [],
  },
]

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug)
}
